#include "configMacros.hpp"


WHITELIST(ON)

WHITELIST_SYSTEM(0)

REGISTER_VEHICLE(veh1, AIR, SLOTS("air1", "air2"))
REGISTER_VEHICLE(veh1, AIR, AIR, SLOTS("air1", "air2"), SLOTS("air3", "air4"))

REGISTER_SLOT("jtac", AIR)


TICKETSYSTEM(ON)

TICKETSYSTEM_MISSIONID(1)
TICKETSYSTEM_MISSIONAME("Test Mission")

TICKETSYSTEM_STUFF(0)

REGISTER_DEFAULT(3)

REGISTER_TICKETCOST("jtac", 5)

REGISTER_TICKETCOST(veh1, 10)